In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV,LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
np.random.seed(0)

In [2]:
df = pd.read_csv('Boston_Data.csv')
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [4]:
y = df[['crim']]
X = df.drop(['crim'],axis=1).astype('float64')
X

,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

Scaling

In [5]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()

X_scaled = scaler.fit_transform(X)

In [6]:
X_train, X_test , y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=0)


X_train.shape,y_train.shape,X_test.shape,y_test.shape

((404, 13), (404, 1), (102, 13), (102, 1))

# Initial Scores - Linear RegressÄ±on

In [7]:
lr = LinearRegression()
lr.fit(X_train,y_train)
prediction = lr.predict(X_test)
test_score = mean_squared_error(y_test,prediction)

prediction_train = lr.predict(X_train)
train_score = -cross_val_score(lr,X_train,y_train,cv=5,scoring='neg_mean_squared_error').mean()
                                
print("train mse : ",train_score, "test mse : ",test_score)

train mse :  39.065683531995234 test mse :  61.400608400849144

# Subset Selection

# Exhaustive Search

In [293]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
# Create Logistic Regression classifier
lr = LinearRegression()
efs = EFS(lr, 
           min_features=1,
           max_features=13,
           scoring='neg_mean_squared_error',
           print_progress=True,
           cv=5)

efs.fit(X_train, y_train)

print('Best MSE score: %.2f' % efs.best_score_ * (-1))
print('Best subset:', efs.best_idx_)

Features: 8191/8191

Best subset: (0, 1, 3, 6, 7, 9, 11, 12)

#   Values are neg_mean_square, the one with abs value smaller, better

In [295]:
efs_analysis = pd.DataFrame.from_dict(efs.get_metric_dict()).T
efs_analysis.sort_values(by = ['avg_score'],ascending = False)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
6176,"(0, 1, 3, 6, 7, 9, 11, 12)","[-17.873326987811296, -11.12098159000189, -128...",-38.1893,"(0, 1, 3, 6, 7, 9, 11, 12)",58.5896,45.5847,22.7923
7387,"(0, 1, 3, 6, 7, 8, 9, 11, 12)","[-17.781986662001753, -11.242507937362113, -12...",-38.2046,"(0, 1, 3, 6, 7, 8, 9, 11, 12)",58.4966,45.5123,22.7562
7422,"(0, 1, 5, 6, 7, 8, 9, 11, 12)","[-18.083316318661883, -11.41633542729895, -129...",-38.2567,"(0, 1, 5, 6, 7, 8, 9, 11, 12)",58.9641,45.8761,22.9381
6253,"(0, 1, 5, 6, 7, 9, 11, 12)","[-18.204127758740864, -11.3217704847302, -129....",-38.2588,"(0, 1, 5, 6, 7, 9, 11, 12)",59.0568,45.9482,22.9741
7372,"(0, 1, 3, 5, 6, 7, 9, 11, 12)","[-18.03311579795969, -11.08635049363585, -129....",-38.2712,"(0, 1, 3, 5, 6, 7, 9, 11, 12)",58.7456,45.7061,22.853
...,...,...,...,...,...,...,...
14,"(0, 2)","[-46.219649464087446, -21.797419094757924, -17...",-63.435,"(0, 2)",74.6057,58.0457,29.0229
0,"(0,)","[-46.60526502620248, -22.03346780563252, -178....",-63.6318,"(0,)",74.9798,58.3368,29.1684
4,"(4,)","[-47.58045977159803, -20.973886283509795, -177...",-63.7179,"(4,)",74.5096,57.971,28.9855
37,"(2, 4)","[-47.35971798592973, -21.22511969502406, -177....",-63.7713,"(2, 4)",74.3225,57.8254,28.9127
2,"(2,)","[-49.353373096873284, -23.126146051541365, -18...",-66.22,"(2,)",75.5875,58.8096,29.4048

Exhaustive Search Does not give much idea, as scores are so close, it basically tries every option

In [8]:
X_train_subset1 = X_train[:,[0,1,3,6,7,9,11,12]]
X_test_subset1 = X_test[:,[0,1,3,6,7,9,11,12]]

In [9]:
lr = LinearRegression()
lr.fit(X_train_subset1,y_train)
prediction = lr.predict(X_test_subset1)
test_score = mean_squared_error(y_test,prediction)

train_score = -cross_val_score(lr,X_train_subset1,y_train,cv=5,scoring='neg_mean_squared_error').mean()
                                
print("train mse : ",train_score, "test mse : ",test_score)

train mse :  38.18934702250674 test mse :  59.508790206445354

# Sequential Forward

In [10]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
lr = LinearRegression()
sfs = SFS(lr,
           k_features=X_train.shape[1],
           forward=True, 
           floating=False, 
           verbose=2,
           scoring='neg_mean_squared_error',
           cv=5)

sfs = sfs.fit(X_train, y_train)
sfs.subsets_

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    0.1s finished

[2020-12-25 23:08:53] Features: 1/13 -- score: -41.68494459581331[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.1s finished

[2020-12-25 23:08:53] Features: 2/13 -- score: -39.34881180165162[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    0.1s finished

[2020-12-25 23:08:53] Features: 3/13 -- score: -39.13914877267886[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished

[2020-12-25 23:08:53] Features: 4/13 -- score: -38.8870903135881[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 5/13 -- score: -38.661719429234886[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 6/13 -- score: -38.31128521913409[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 7/13 -- score: -38.27540962321594[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 8/13 -- score: -38.18934702250674[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 9/13 -- score: -38.20462229625687[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 10/13 -- score: -38.28116564592468[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 11/13 -- score: -38.355063451848736[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 12/13 -- score: -38.597651379792346[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

[2020-12-25 23:08:54] Features: 13/13 -- score: -39.065683531995234

{1: {'feature_idx': (7,),
  'cv_scores': array([ -19.88565823,  -12.00553153, -136.7052133 ,  -12.8651705 ,
          -26.96314943]),
  'avg_score': -41.68494459581331,
  'feature_names': ('7',)},
 2: {'feature_idx': (7, 11),
  'cv_scores': array([ -19.43639904,  -10.13770221, -132.73958729,  -10.52823382,
          -23.90213665]),
  'avg_score': -39.34881180165162,
  'feature_names': ('7', '11')},
 3: {'feature_idx': (0, 7, 11),
  'cv_scores': array([ -19.43281014,  -10.04533632, -132.31673756,  -10.42147466,
          -23.47938518]),
  'avg_score': -39.13914877267886,
  'feature_names': ('0', '7', '11')},
 4: {'feature_idx': (0, 6, 7, 11),
  'cv_scores': array([ -19.07159787,   -9.88109792, -131.78257132,  -10.31628449,
          -23.38389997]),
  'avg_score': -38.8870903135881,
  'feature_names': ('0', '6', '7', '11')},
 5: {'feature_idx': (0, 1, 6, 7, 11),
  'cv_scores': array([ -19.15458393,   -9.80345848, -131.37869382,  -10.10094366,
          -22.87091726]),
  'avg_score': -38.661719429234886,
  'feature_names': ('0', '1', '6', '7', '11')},
 6: {'feature_idx': (0, 1, 6, 7, 11, 12),
  'cv_scores': array([ -18.08292408,  -11.28161166, -129.68865753,   -9.43623942,
          -23.06699341]),
  'avg_score': -38.31128521913409,
  'feature_names': ('0', '1', '6', '7', '11', '12')},
 7: {'feature_idx': (0, 1, 3, 6, 7, 11, 12),
  'cv_scores': array([ -18.01280407,  -11.05928841, -129.3450683 ,   -9.77592242,
          -23.18396492]),
  'avg_score': -38.27540962321594,
  'feature_names': ('0', '1', '3', '6', '7', '11', '12')},
 8: {'feature_idx': (0, 1, 3, 6, 7, 9, 11, 12),
  'cv_scores': array([ -17.87332699,  -11.12098159, -128.8664008 ,  -10.0265616 ,
          -23.05946414]),
  'avg_score': -38.18934702250674,
  'feature_names': ('0', '1', '3', '6', '7', '9', '11', '12')},
 9: {'feature_idx': (0, 1, 3, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.78198666,  -11.24250794, -128.76255483,  -10.28916657,
          -22.94689548]),
  'avg_score': -38.20462229625687,
  'feature_names': ('0', '1', '3', '6', '7', '8', '9', '11', '12')},
 10: {'feature_idx': (0, 1, 2, 3, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.94170499,  -11.11890854, -128.6978247 ,  -10.22439675,
          -23.42299326]),
  'avg_score': -38.28116564592468,
  'feature_names': ('0', '1', '2', '3', '6', '7', '8', '9', '11', '12')},
 11: {'feature_idx': (0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -18.06904607,  -11.09724973, -128.97370514,  -10.16735248,
          -23.46796384]),
  'avg_score': -38.355063451848736,
  'feature_names': ('0', '1', '2', '3', '5', '6', '7', '8', '9', '11', '12')},
 12: {'feature_idx': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.77842688,  -13.44480467, -128.36000967,  -10.03461441,
          -23.37040127]),
  'avg_score': -38.597651379792346,
  'feature_names': ('0',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '11',
   '12')},
 13: {'feature_idx': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
  'cv_scores': array([ -19.07055544,  -13.57553116, -129.21452627,  -10.06401953,
          -23.40378526]),
  'avg_score': -39.065683531995234,
  'feature_names': ('0',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '10',
   '11',
   '12')}}

In [11]:
sfs_an1 = pd.DataFrame.from_dict(sfs.get_metric_dict()).T
sfs_an1.sort_values(by = ['avg_score'],ascending = False)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
8,"(0, 1, 3, 6, 7, 9, 11, 12)","[-17.873326987811296, -11.12098159000189, -128...",-38.1893,"(0, 1, 3, 6, 7, 9, 11, 12)",58.5896,45.5847,22.7923
9,"(0, 1, 3, 6, 7, 8, 9, 11, 12)","[-17.781986662001753, -11.242507937362113, -12...",-38.2046,"(0, 1, 3, 6, 7, 8, 9, 11, 12)",58.4966,45.5123,22.7562
7,"(0, 1, 3, 6, 7, 11, 12)","[-18.01280407459043, -11.059288406857357, -129...",-38.2754,"(0, 1, 3, 6, 7, 11, 12)",58.8572,45.7929,22.8964
10,"(0, 1, 2, 3, 6, 7, 8, 9, 11, 12)","[-17.941704985059452, -11.118908539726313, -12...",-38.2812,"(0, 1, 2, 3, 6, 7, 8, 9, 11, 12)",58.4337,45.4634,22.7317
6,"(0, 1, 6, 7, 11, 12)","[-18.082924077910043, -11.281611658070991, -12...",-38.3113,"(0, 1, 6, 7, 11, 12)",59.0556,45.9473,22.9736
11,"(0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12)","[-18.06904607401455, -11.097249728100904, -128...",-38.3551,"(0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12)",58.5687,45.5685,22.7842
12,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12)","[-17.77842688496364, -13.444804668120051, -128...",-38.5977,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12)",57.9696,45.1023,22.5512
5,"(0, 1, 6, 7, 11)","[-19.154583926091043, -9.803458480832074, -131...",-38.6617,"(0, 1, 6, 7, 11)",59.9415,46.6365,23.3183
4,"(0, 6, 7, 11)","[-19.07159787368382, -9.881097922040784, -131....",-38.8871,"(0, 6, 7, 11)",60.0664,46.7337,23.3669
13,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)","[-19.070555440010832, -13.575531163099301, -12...",-39.0657,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)",58.2302,45.3051,22.6525
3,"(0, 7, 11)","[-19.432810139770687, -10.045336320256542, -13...",-39.1391,"(0, 7, 11)",60.2493,46.876,23.438
2,"(7, 11)","[-19.436399042514697, -10.137702208528218, -13...",-39.3488,"(7, 11)",60.3973,46.9912,23.4956
1,"(7,)","[-19.885658226778716, -12.005531525155195, -13...",-41.6849,"(7,)",61.4585,47.8168,23.9084

Same Subset

In [13]:
# Same subset, yet I have named it subset2
X_train_subset2 = X_train[:,[0,1,3,6,7,9,11,12]]
X_test_subset2 = X_test[:,[0,1,3,6,7,9,11,12]]

In [14]:
lr = LinearRegression()
lr.fit(X_train_subset2,y_train)
prediction = lr.predict(X_test_subset2)
test_score = mean_squared_error(y_test,prediction)

train_score = -cross_val_score(lr,X_train_subset2,y_train,cv=5,scoring='neg_mean_squared_error').mean()
                                
print("train mse : ",train_score, "test mse : ",test_score)

train mse :  38.18934702250674 test mse :  59.508790206445354

# Sequential Backward

In [15]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
lr = LinearRegression()
sfs = SFS(lr,
           k_features=1,
           forward=False, 
           floating=False, 
           verbose=2,
           scoring='neg_mean_squared_error',
           cv=5)

sfs = sfs.fit(X_train, y_train)
sfs.subsets_

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    0.1s finished

[2020-12-25 23:09:46] Features: 12/1 -- score: -38.597651379792346[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.1s finished

[2020-12-25 23:09:47] Features: 11/1 -- score: -38.355063451848736[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    0.1s finished

[2020-12-25 23:09:47] Features: 10/1 -- score: -38.28116564592468[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished

[2020-12-25 23:09:47] Features: 9/1 -- score: -38.20462229625687[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.0s finished

[2020-12-25 23:09:47] Features: 8/1 -- score: -38.18934702250674[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.0s finished

[2020-12-25 23:09:47] Features: 7/1 -- score: -38.27540962321594[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.0s finished

[2020-12-25 23:09:47] Features: 6/1 -- score: -38.31128521913409[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s finished

[2020-12-25 23:09:47] Features: 5/1 -- score: -38.58121934592971[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2020-12-25 23:09:48] Features: 4/1 -- score: -39.008572941152764[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2020-12-25 23:09:48] Features: 3/1 -- score: -39.802226232880585[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2020-12-25 23:09:48] Features: 2/1 -- score: -40.11339333527656[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2020-12-25 23:09:48] Features: 1/1 -- score: -41.68494459581331

{13: {'feature_idx': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
  'cv_scores': array([ -19.07055544,  -13.57553116, -129.21452627,  -10.06401953,
          -23.40378526]),
  'avg_score': -39.065683531995234,
  'feature_names': ('0',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '10',
   '11',
   '12')},
 12: {'feature_idx': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.77842688,  -13.44480467, -128.36000967,  -10.03461441,
          -23.37040127]),
  'avg_score': -38.597651379792346,
  'feature_names': ('0',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '11',
   '12')},
 11: {'feature_idx': (0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -18.06904607,  -11.09724973, -128.97370514,  -10.16735248,
          -23.46796384]),
  'avg_score': -38.355063451848736,
  'feature_names': ('0', '1', '2', '3', '5', '6', '7', '8', '9', '11', '12')},
 10: {'feature_idx': (0, 1, 2, 3, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.94170499,  -11.11890854, -128.6978247 ,  -10.22439675,
          -23.42299326]),
  'avg_score': -38.28116564592468,
  'feature_names': ('0', '1', '2', '3', '6', '7', '8', '9', '11', '12')},
 9: {'feature_idx': (0, 1, 3, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.78198666,  -11.24250794, -128.76255483,  -10.28916657,
          -22.94689548]),
  'avg_score': -38.20462229625687,
  'feature_names': ('0', '1', '3', '6', '7', '8', '9', '11', '12')},
 8: {'feature_idx': (0, 1, 3, 6, 7, 9, 11, 12),
  'cv_scores': array([ -17.87332699,  -11.12098159, -128.8664008 ,  -10.0265616 ,
          -23.05946414]),
  'avg_score': -38.18934702250674,
  'feature_names': ('0', '1', '3', '6', '7', '9', '11', '12')},
 7: {'feature_idx': (0, 1, 3, 6, 7, 11, 12),
  'cv_scores': array([ -18.01280407,  -11.05928841, -129.3450683 ,   -9.77592242,
          -23.18396492]),
  'avg_score': -38.27540962321594,
  'feature_names': ('0', '1', '3', '6', '7', '11', '12')},
 6: {'feature_idx': (0, 1, 6, 7, 11, 12),
  'cv_scores': array([ -18.08292408,  -11.28161166, -129.68865753,   -9.43623942,
          -23.06699341]),
  'avg_score': -38.31128521913409,
  'feature_names': ('0', '1', '6', '7', '11', '12')},
 5: {'feature_idx': (0, 1, 6, 7, 12),
  'cv_scores': array([ -17.45895239,  -12.21258001, -129.33518835,   -9.95025372,
          -23.94912226]),
  'avg_score': -38.58121934592971,
  'feature_names': ('0', '1', '6', '7', '12')},
 4: {'feature_idx': (0, 6, 7, 12),
  'cv_scores': array([ -17.67793882,  -12.37431513, -130.19326652,  -10.38117731,
          -24.41616693]),
  'avg_score': -39.008572941152764,
  'feature_names': ('0', '6', '7', '12')},
 3: {'feature_idx': (6, 7, 12),
  'cv_scores': array([ -18.29832571,  -12.30616029, -132.11802533,  -10.92189855,
          -25.36672128]),
  'avg_score': -39.802226232880585,
  'feature_names': ('6', '7', '12')},
 2: {'feature_idx': (7, 12),
  'cv_scores': array([ -18.38639448,  -12.52146096, -132.60458136,  -11.42933146,
          -25.62519842]),
  'avg_score': -40.11339333527656,
  'feature_names': ('7', '12')},
 1: {'feature_idx': (7,),
  'cv_scores': array([ -19.88565823,  -12.00553153, -136.7052133 ,  -12.8651705 ,
          -26.96314943]),
  'avg_score': -41.68494459581331,
  'feature_names': ('7',)}}

In [16]:
sfs_an2 = pd.DataFrame.from_dict(sfs.get_metric_dict()).T
sfs_an2.sort_values(by = ['avg_score'],ascending = False)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
8,"(0, 1, 3, 6, 7, 9, 11, 12)","[-17.873326987811296, -11.12098159000189, -128...",-38.1893,"(0, 1, 3, 6, 7, 9, 11, 12)",58.5896,45.5847,22.7923
9,"(0, 1, 3, 6, 7, 8, 9, 11, 12)","[-17.781986662001753, -11.242507937362113, -12...",-38.2046,"(0, 1, 3, 6, 7, 8, 9, 11, 12)",58.4966,45.5123,22.7562
7,"(0, 1, 3, 6, 7, 11, 12)","[-18.01280407459043, -11.059288406857357, -129...",-38.2754,"(0, 1, 3, 6, 7, 11, 12)",58.8572,45.7929,22.8964
10,"(0, 1, 2, 3, 6, 7, 8, 9, 11, 12)","[-17.941704985059452, -11.118908539726313, -12...",-38.2812,"(0, 1, 2, 3, 6, 7, 8, 9, 11, 12)",58.4337,45.4634,22.7317
6,"(0, 1, 6, 7, 11, 12)","[-18.082924077910043, -11.281611658070991, -12...",-38.3113,"(0, 1, 6, 7, 11, 12)",59.0556,45.9473,22.9736
11,"(0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12)","[-18.06904607401455, -11.097249728100904, -128...",-38.3551,"(0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12)",58.5687,45.5685,22.7842
5,"(0, 1, 6, 7, 12)","[-17.458952385514618, -12.212580010067631, -12...",-38.5812,"(0, 1, 6, 7, 12)",58.6509,45.6324,22.8162
12,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12)","[-17.77842688496364, -13.444804668120051, -128...",-38.5977,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12)",57.9696,45.1023,22.5512
4,"(0, 6, 7, 12)","[-17.67793882044957, -12.37431512578081, -130....",-39.0086,"(0, 6, 7, 12)",58.9317,45.8508,22.9254
13,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)","[-19.070555440010832, -13.575531163099301, -12...",-39.0657,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)",58.2302,45.3051,22.6525
3,"(6, 7, 12)","[-18.29832571321311, -12.306160287551442, -132...",-39.8022,"(6, 7, 12)",59.6882,46.4395,23.2197
2,"(7, 12)","[-18.386394478881485, -12.521460958070271, -13...",-40.1134,"(7, 12)",59.7921,46.5203,23.2601
1,"(7,)","[-19.885658226778716, -12.005531525155195, -13...",-41.6849,"(7,)",61.4585,47.8168,23.9084

Same results with forward subset selection. So subsets are same, no need for score calculation

# I have tested model selection in linear regression, picked columns are : 
# [0,1,3,6,7,9,11,12]

# RIDGE

In [17]:
alphas = 10**np.linspace(5,-2,100)*0.5
alphas

array([5.00000000e+04, 4.24876718e+04, 3.61040451e+04, 3.06795364e+04,
       2.60700414e+04, 2.21531073e+04, 1.88246790e+04, 1.59963357e+04,
       1.35929412e+04, 1.15506485e+04, 9.81520325e+03, 8.34050269e+03,
       7.08737081e+03, 6.02251770e+03, 5.11765511e+03, 4.34874501e+03,
       3.69536102e+03, 3.14014572e+03, 2.66834962e+03, 2.26743925e+03,
       1.92676430e+03, 1.63727458e+03, 1.39127970e+03, 1.18224471e+03,
       1.00461650e+03, 8.53676324e+02, 7.25414389e+02, 6.16423370e+02,
       5.23807876e+02, 4.45107543e+02, 3.78231664e+02, 3.21403656e+02,
       2.73113861e+02, 2.32079442e+02, 1.97210303e+02, 1.67580133e+02,
       1.42401793e+02, 1.21006413e+02, 1.02825615e+02, 8.73764200e+01,
       7.42484131e+01, 6.30928442e+01, 5.36133611e+01, 4.55581378e+01,
       3.87131841e+01, 3.28966612e+01, 2.79540509e+01, 2.37540508e+01,
       2.01850863e+01, 1.71523464e+01, 1.45752653e+01, 1.23853818e+01,
       1.05245207e+01, 8.94324765e+00, 7.59955541e+00, 6.45774833e+00,
       5.48749383e+00, 4.66301673e+00, 3.96241449e+00, 3.36707533e+00,
       2.86118383e+00, 2.43130079e+00, 2.06600620e+00, 1.75559587e+00,
       1.49182362e+00, 1.26768225e+00, 1.07721735e+00, 9.15369140e-01,
       7.77838072e-01, 6.60970574e-01, 5.61662016e-01, 4.77274228e-01,
       4.05565415e-01, 3.44630605e-01, 2.92851041e-01, 2.48851178e-01,
       2.11462144e-01, 1.79690683e-01, 1.52692775e-01, 1.29751211e-01,
       1.10256537e-01, 9.36908711e-02, 7.96141397e-02, 6.76523887e-02,
       5.74878498e-02, 4.88504979e-02, 4.15108784e-02, 3.52740116e-02,
       2.99742125e-02, 2.54706901e-02, 2.16438064e-02, 1.83918989e-02,
       1.56285792e-02, 1.32804389e-02, 1.12850986e-02, 9.58955131e-03,
       8.14875417e-03, 6.92443186e-03, 5.88405976e-03, 5.00000000e-03])

At previous stage, I have already scaled the Data.

In [18]:
ridgecv = RidgeCV(alphas = alphas,cv = 5, scoring = 'neg_mean_squared_error')
ridgecv.fit(X_train, y_train)
ridgecv.alpha_

8.943247645287176

In [19]:
ridge5 = Ridge(alpha = ridgecv.alpha_)
ridge5.fit(X_train, y_train)
test_score = mean_squared_error(y_test, ridge5.predict(X_test))
train_score = -cross_val_score(ridge5,X_train,y_train,cv=5,scoring='neg_mean_squared_error').mean()

print("train mse : ",train_score, " test mse : ",test_score)

train mse :  38.947182194124466  test mse :  61.35138145645922

# LR Selected Features (from previous step) on Ridge
# X_train_subset1

In [20]:
ridge6 = Ridge(alpha = ridgecv.alpha_)
ridge6.fit(X_train_subset1,y_train)
prediction = ridge6.predict(X_test_subset1)
test_score = mean_squared_error(y_test,prediction)


train_score = -cross_val_score(ridge6,X_train_subset1,y_train,cv=5,scoring='neg_mean_squared_error').mean()
                                
print("train mse : ",train_score, "test mse : ",test_score)

train mse :  38.14040833186057 test mse :  59.97171963632714

# Ridge Selected Features

In [21]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
lr = Ridge()
sfs = SFS(lr,
           k_features=1,
           forward=False, 
           floating=False, 
           verbose=2,
           scoring='neg_mean_squared_error',
           cv=5)

sfs = sfs.fit(X_train, y_train)
sfs.subsets_

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    0.1s finished

[2020-12-25 23:12:08] Features: 12/1 -- score: -38.56666732411636[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.1s finished

[2020-12-25 23:12:08] Features: 11/1 -- score: -38.32797704388799[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    0.1s finished

[2020-12-25 23:12:08] Features: 10/1 -- score: -38.25683878502976[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished

[2020-12-25 23:12:08] Features: 9/1 -- score: -38.184756536209264[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.0s finished

[2020-12-25 23:12:08] Features: 8/1 -- score: -38.17495051601536[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.0s finished

[2020-12-25 23:12:08] Features: 7/1 -- score: -38.26557839273084[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.0s finished

[2020-12-25 23:12:09] Features: 6/1 -- score: -38.30528994535622[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s finished

[2020-12-25 23:12:09] Features: 5/1 -- score: -38.579775417342596[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2020-12-25 23:12:09] Features: 4/1 -- score: -39.0039314420233[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2020-12-25 23:12:09] Features: 3/1 -- score: -39.79744157924189[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2020-12-25 23:12:09] Features: 2/1 -- score: -40.10872962432317[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2020-12-25 23:12:09] Features: 1/1 -- score: -41.67928384736011

{13: {'feature_idx': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
  'cv_scores': array([ -19.03727723,  -13.45946934, -129.38325603,   -9.87810618,
          -23.40327227]),
  'avg_score': -39.03227621086596,
  'feature_names': ('0',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '10',
   '11',
   '12')},
 12: {'feature_idx': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.77085718,  -13.34143274, -128.50454255,   -9.85614128,
          -23.36036286]),
  'avg_score': -38.56666732411636,
  'feature_names': ('0',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '11',
   '12')},
 11: {'feature_idx': (0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -18.0691751 ,  -11.0056054 , -129.1163555 ,  -10.00547174,
          -23.44327748]),
  'avg_score': -38.32797704388799,
  'feature_names': ('0', '1', '2', '3', '5', '6', '7', '8', '9', '11', '12')},
 10: {'feature_idx': (0, 1, 2, 3, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.94529058,  -11.02649455, -128.84887489,  -10.06336084,
          -23.40017306]),
  'avg_score': -38.25683878502976,
  'feature_names': ('0', '1', '2', '3', '6', '7', '8', '9', '11', '12')},
 9: {'feature_idx': (0, 1, 3, 6, 7, 8, 9, 11, 12),
  'cv_scores': array([ -17.78862221,  -11.14777495, -128.91379385,  -10.13533386,
          -22.9382578 ]),
  'avg_score': -38.184756536209264,
  'feature_names': ('0', '1', '3', '6', '7', '8', '9', '11', '12')},
 8: {'feature_idx': (0, 1, 3, 6, 7, 9, 11, 12),
  'cv_scores': array([ -17.86325751,  -11.05673466, -128.99222374,   -9.93625408,
          -23.02628259]),
  'avg_score': -38.17495051601536,
  'feature_names': ('0', '1', '3', '6', '7', '9', '11', '12')},
 7: {'feature_idx': (0, 1, 3, 6, 7, 11, 12),
  'cv_scores': array([ -18.00363815,  -11.01046507, -129.44925683,   -9.70772044,
          -23.15681148]),
  'avg_score': -38.26557839273084,
  'feature_names': ('0', '1', '3', '6', '7', '11', '12')},
 6: {'feature_idx': (0, 1, 6, 7, 11, 12),
  'cv_scores': array([ -18.07336299,  -11.23173435, -129.77479   ,   -9.39323834,
          -23.05332404]),
  'avg_score': -38.30528994535622,
  'feature_names': ('0', '1', '6', '7', '11', '12')},
 5: {'feature_idx': (0, 1, 6, 7, 12),
  'cv_scores': array([ -17.45025731,  -12.16518084, -129.43930114,   -9.90305833,
          -23.94107947]),
  'avg_score': -38.579775417342596,
  'feature_names': ('0', '1', '6', '7', '12')},
 4: {'feature_idx': (0, 6, 7, 12),
  'cv_scores': array([ -17.67590524,  -12.33492534, -130.27271031,  -10.33302136,
          -24.40309495]),
  'avg_score': -39.0039314420233,
  'feature_names': ('0', '6', '7', '12')},
 3: {'feature_idx': (6, 7, 12),
  'cv_scores': array([ -18.30234655,  -12.278367  , -132.18149642,  -10.87204316,
          -25.35295477]),
  'avg_score': -39.79744157924189,
  'feature_names': ('6', '7', '12')},
 2: {'feature_idx': (7, 12),
  'cv_scores': array([ -18.38992157,  -12.48827484, -132.67475776,  -11.37971272,
          -25.61098122]),
  'avg_score': -40.10872962432317,
  'feature_names': ('7', '12')},
 1: {'feature_idx': (7,),
  'cv_scores': array([ -19.89627413,  -11.96333184, -136.79088419,  -12.8018997 ,
          -26.94402937]),
  'avg_score': -41.67928384736011,
  'feature_names': ('7',)}}

In [22]:
sfs_an1 = pd.DataFrame.from_dict(sfs.get_metric_dict()).T
sfs_an1.sort_values(by = ['avg_score'],ascending = False)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
8,"(0, 1, 3, 6, 7, 9, 11, 12)","[-17.86325750979941, -11.056734664112584, -128...",-38.175,"(0, 1, 3, 6, 7, 9, 11, 12)",58.6821,45.6566,22.8283
9,"(0, 1, 3, 6, 7, 8, 9, 11, 12)","[-17.788622213506436, -11.147774948132216, -12...",-38.1848,"(0, 1, 3, 6, 7, 8, 9, 11, 12)",58.6126,45.6026,22.8013
10,"(0, 1, 2, 3, 6, 7, 8, 9, 11, 12)","[-17.945290577886386, -11.026494548838624, -12...",-38.2568,"(0, 1, 2, 3, 6, 7, 8, 9, 11, 12)",58.5522,45.5556,22.7778
7,"(0, 1, 3, 6, 7, 11, 12)","[-18.003638148127827, -11.010465065657968, -12...",-38.2656,"(0, 1, 3, 6, 7, 11, 12)",58.9322,45.8512,22.9256
6,"(0, 1, 6, 7, 11, 12)","[-18.07336299175556, -11.231734353043773, -129...",-38.3053,"(0, 1, 6, 7, 11, 12)",59.1164,45.9946,22.9973
11,"(0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12)","[-18.069175100469977, -11.005605401411515, -12...",-38.328,"(0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12)",58.6836,45.6578,22.8289
12,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12)","[-17.770857183823214, -13.341432739143169, -12...",-38.5667,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12)",58.0893,45.1954,22.5977
5,"(0, 1, 6, 7, 12)","[-17.45025730587763, -12.165180836914672, -129...",-38.5798,"(0, 1, 6, 7, 12)",58.7205,45.6865,22.8433
4,"(0, 6, 7, 12)","[-17.675905243657873, -12.334925337718282, -13...",-39.0039,"(0, 6, 7, 12)",58.9872,45.894,22.947
13,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)","[-19.037277225655135, -13.459469342283812, -12...",-39.0323,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)",58.3678,45.4121,22.7061
3,"(6, 7, 12)","[-18.302346549325495, -12.27836699547418, -132...",-39.7974,"(6, 7, 12)",59.7335,46.4747,23.2373
2,"(7, 12)","[-18.389921573773584, -12.488274844829247, -13...",-40.1087,"(7, 12)",59.8416,46.5588,23.2794
1,"(7,)","[-19.896274128586445, -11.963331843693677, -13...",-41.6793,"(7,)",61.5191,47.8639,23.932

# Ridge Selected Features turned out to be same, same results...

In [23]:
ridge6 = Ridge(alpha = ridgecv.alpha_)
ridge6.fit(X_train_subset1,y_train)
prediction = ridge6.predict(X_test_subset1)
test_score = mean_squared_error(y_test,prediction)


train_score = -cross_val_score(ridge6,X_train_subset1,y_train,cv=5,scoring='neg_mean_squared_error').mean()
                                
print("train mse : ",train_score, "test mse : ",test_score)

train mse :  38.14040833186057 test mse :  59.97171963632714

# Lasso

In [24]:
lassocv = LassoCV(alphas = alphas, cv = 5)
lassocv.fit(X_train, y_train)
lassocv.alpha_

E:\anaconda\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

0.009589551308362443

In [25]:
l1 = Lasso(alpha=lassocv.alpha_)
l1.fit(X_train,y_train)

prediction = l1.predict(X_test)
test_score = mean_squared_error(y_test,prediction)


train_score = -cross_val_score(l1,X_train,y_train,cv=5,scoring='neg_mean_squared_error').mean()

print("train mse : ",train_score," test mse : ",test_score)

train mse :  39.056307408607935  test mse :  61.197901403212555

# Lasso On Subset (It is also turn out to be same subset)

In [26]:
l2 = Lasso(alpha=lassocv.alpha_)
l2.fit(X_train_subset1,y_train)

prediction = l2.predict(X_test_subset1)
test_score = mean_squared_error(y_test,prediction)

train_score = -cross_val_score(l2,X_train_subset1,y_train,cv=5,scoring='neg_mean_squared_error').mean()

print("train mse : ",train_score," test mse : ",test_score)

train mse :  38.194716537681636  test mse :  59.57456818498601

# REPORT IS ADDED PDF FILE